#ifndef KS_PROCESS_TABLE_H
#define KS_PROCESS_TABLE_H

#include <stdbool.h>
#include "evidence_graph.h"
#include <stdint.h>

#include "../../include/ks_event.h"

#define KS_MAX_PROCESSES 8192

/*
 * Behavioral evidence maintained for every active process.
 *
 * This is deliberately independent of the final alert schema.
 * The detector can evolve internally without changing ks_alert.
 */
typedef struct {

    bool active;

    uint32_t pid;
    uint32_t ppid;

    uint32_t uid;
    uint32_t gid;

    uint64_t start_time_ns;
    uint64_t end_time_ns;
    uint64_t last_activity_ns;

    /*
     * Behavioral counters.
     */
    uint32_t exec_count;
    uint32_t network_count;
    uint32_t file_open_count;
    uint32_t file_write_count;
    uint32_t file_create_count;
    uint32_t privilege_event_count;

    /*
     * Temporal evidence.
     */
    uint64_t last_exec_ns;
    uint64_t last_network_ns;
    uint64_t last_file_write_ns;
    uint64_t last_privilege_ns;

    /*
     * Behavioral transitions.
     */
    bool spawned_shell;
    bool made_network_connection;
    bool wrote_file;
    bool created_file;
    bool privilege_transition;

    /*
     * File-chain correlation evidence.
     *
     * These fields allow KernelShield to distinguish ordinary
     * file activity from a multi-stage drop-and-execute pattern.
     */
    bool temporary_file_created;
    bool temporary_file_written;
    bool file_execution_observed;

    char tracked_file_path[KS_MAX_PATH_LEN];

    uint64_t temporary_file_create_ns;
    uint64_t temporary_file_write_ns;
    uint64_t file_execution_ns;

    /*
     * Correlation state.
     */
    bool attack_chain_detected;

    /*
     * Per-detection alert deduplication.
     *
     * A detection in one category must not suppress a
     * different detection generated by the same process.
     */
    bool file_alert_emitted;
    bool privilege_alert_emitted;
    bool network_alert_emitted;
    bool chain_alert_emitted;

    /*
     * Internal behavioral score.
     *
     * This is NOT exported as a formal risk score in ks_alert.
     * It is an internal decision signal.
     */
    int behavioral_score;

    /*
     * Independent evidence accumulated during the current
     * process episode.
     */
    ks_evidence_graph evidence_graph;

    /*
     * Behavioral episode state.
     *
     * An episode groups temporally related activity from the
     * same process lineage into one detection unit.
     */
    uint32_t episode_id;
    uint64_t episode_start_ns;
    uint64_t episode_last_event_ns;
    uint32_t episode_event_count;
    uint32_t episode_score;

    /*
     * Execution transition history.
     */
    char previous_comm[TASK_COMM_LEN];
    char previous_filename[KS_MAX_FILENAME_LEN];

    char comm[TASK_COMM_LEN];
    char filename[KS_MAX_FILENAME_LEN];

} ks_process;

void ks_process_table_init(void);

void ks_process_add(const struct ks_event *event);

void ks_process_remove(const struct ks_event *event);

ks_process *ks_process_find(uint32_t pid);

void ks_process_table_print(void);

#endif
