input {
  file {
    path => "/var/log/kernelshield/kernelshield-events.jsonl"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    codec => json
  }
}

output {
  elasticsearch {
    hosts => ["https://localhost:9200"]
    user => "elastic"
    password => "${ELASTIC_PASSWORD}"
    ssl_enabled => true
    ssl_verification_mode => "none"
    index => "kernelshield-logs"
  }

  stdout {
    codec => rubydebug
  }
}
