input {
  file {
    path => "/var/log/kernelshield/kernelshield-events.jsonl"
    start_position => "end"
    sincedb_path => "/dev/null"
    codec => json
    tags => ["kernelshield_event"]
  }

  file {
    path => "/var/log/kernelshield/alerts.jsonl"
    start_position => "end"
    sincedb_path => "/dev/null"
    codec => json
    tags => ["kernelshield_alert"]
  }
}

output {
  if "kernelshield_alert" in [tags] {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "kernelshield-alerts-v2"
    }
  } else if "kernelshield_event" in [tags] {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "kernelshield-logs-v2"
    }
  }

  stdout {
    codec => rubydebug
  }
}
